### ISSUE TITLE
enums not properly handled in stack

### ISSUE THREAD

**Issue by amir-arad** [wix/mutable#6]
@arnonkehat says:
enums not properly handled in stack
I tried use an enum in a dropdown, and could not use its values as the dropdown items. talk to me if you want to see what I was trying to do.

**Comment by amir-arad** [comment]
@arnonkehat  says:
enums not properly handled in stack
I tried use an enum in a dropdown, and could not use its values as the dropdown items. talk to me if you want to see what I was trying to do.

**Comment by amir-arad** [comment]
@arnonkehat please provide example code

**Comment by arnonkehat** [comment]
OK. I found the code to reproduce and it's giving a much better error now that indicates it's in the component. come and see if you want.
